// <auto-generated />
namespace MvcMusicStore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class update_album : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_album));
        
        string IMigrationMetadata.Id
        {
            get { return "201704040844102_update_album"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
