// <auto-generated />
namespace MvcMusicStore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_band : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_band));
        
        string IMigrationMetadata.Id
        {
            get { return "201704041151011_add_band"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
